name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore SCLOCUA.csproj
    - name: Build
      run: dotnet build SCLOCUA.csproj -c Release --no-restore
    - name: Test
      run: dotnet test SCLOCUA.csproj -c Release --no-build
